version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - appointments-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://spring_demo-postgres:5432/appointments
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  spring_demo-postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - appointments_db_data:/var/lib/postgresql/data

volumes:
  appointments_db_data: